########################################################
name: train
gpu_rank: '0'
device: cuda:0
output_mode: 'single'
size: 512
up_factor: 1
degeneration_w0: 2.4
noise_level: 10
denoise: train
read_LR: True
read_version: "new"
net_G:
  initialize: True
  input_channels: 1
  model_decouple_name: Unet
  model_decouple_pretrain: False
  # pixel loss fea_loss feq_loss grad_loss corr_loss adv_loss
  weight_decouple: [1, 0, 0, 0, 0, 1]
  mode_decouple: GAN
  pretrain_dir: None #D:\CQL\codes\microscopy_decouple\validation\DSRM_Microtubes_Mitochondria_lysosome_noise_level_800\weights\1\main_G.pth
  #D:\CQL\codes\microscopy_decouple\validation\DSRM_Microtubes_Mitochondria_noise_level_800_invariant_invariant\weights\1\main_G.pth
  #D:\CQL\codes\microscopy_decouple\validation\DSRM_Microtubes_Mitochondria_noise_level_200_corr_0_Unet\weights\1\main_G.pth
  #D:\CQL\codes\microscopy_decouple\validation\Microtubes_Mitochondria_level_0_Unet_G.pth
  
net_D:
  model_name: UnetD 
  pretrain_dir_1: None #D:\CQL\codes\microscopy_decouple\validation\DSRM_Microtubes_Mitochondria_lysosome_noise_level_800\weights\1\main_D.pth
  pretrain_dir_2: None
   #D:\CQL\codes\microscopy_decouple\validation\DSRM_Microtubes_Mitochondria_noise_level_800_invariant_invariant\weights\1\main_D.pth
  #D:\CQL\codes\microscopy_decouple\validation\DSRM_Microtubes_Mitochondria_noise_level_200_corr_0_Unet\weights\1\main_D.pth
  #D:\CQL\codes\microscopy_decouple\validation\Microtubes_Mitochondria_level_0_Unet_D.pth

num_train: 2
num_test: 2
train:
  mean: [0.0]
  std: [50.0]
  lr_G: 0.00001
  lr_D: 0.0000001
  index_per_D: 2
  epoches: 2000
  epoches_per_val: 1
  epoches_per_save: 1
  batch_size: 1
  num_iter: 1
  optimizer: Adam
  scheduler: CosineAnnealingLR
  #CosineAnnealingLR
  #OneCycleLR
  #CosineAnnealingLR

train_dir_LR: data\train_LR
test_dir_LR: data\test_LR
train_dir_HR: data\train_HR #_deconv
test_dir_HR: data\test_HR #_deconv

validation_dir: validation
validation_list: ['loss_plots', 'weights', 'excels', 'validation_images']
validation_date: DSCM_Micro_Lyso_noise_level_10_2.4
test_list: []
test_read_list: None
test_save_dir: None

category: ['Micro', 'Lyso']
output_type: 'split'
output_list: ['Micro', 'Lyso']
factor_list: [1, 1]
########################################################